name: Fetch Weather and Post to Tandem

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Manual trigger (optional)

jobs:
  update_and_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Write weather fetcher script
        run: |
          echo "import requests" > fetch_weather.py
          echo "import json" >> fetch_weather.py
          echo "" >> fetch_weather.py
          echo "API_KEY = '0b4192116572f42a2606602c1a8d46c2'" >> fetch_weather.py
          echo "CITY = 'Delft'" >> fetch_weather.py
          echo "url = f'https://api.openweathermap.org/data/2.5/weather?q={CITY}&appid={API_KEY}&units=metric'" >> fetch_weather.py
          echo "r = requests.get(url)" >> fetch_weather.py
          echo "d = r.json()" >> fetch_weather.py
          echo "" >> fetch_weather.py
          echo "with open('stream.json', 'w') as f:" >> fetch_weather.py
          echo "    json.dump({" >> fetch_weather.py
          echo "        'temperature': d['main']['temp']," >> fetch_weather.py
          echo "        'humidity': d['main']['humidity']" >> fetch_weather.py
          echo "    }, f, indent=2)" >> fetch_weather.py

      - name: Run the script
        run: python fetch_weather.py

      - name: Commit stream.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add stream.json
          git commit -m "Update stream.json with new weather data" || echo "No changes to commit"
          git push

      - name: Send JSON Data to Tandem (Temperature)
        run: |
          curl -X POST "https://:059UiG4ZQYeDvz9PoW600w@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:ST5-WSDoQcm5VZSn84_kGQ/streams/AQAAAKyrPhWZC0GUrXd18gpY0CoAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON Data to Tandem (Humidity)
        run: |
          curl -X POST "https://:LA1-6cosQUCKzXPl1h7E5A@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:ST5-WSDoQcm5VZSn84_kGQ/streams/AQAAAHiguQoVW0iXhe77Q_4n9vcAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json
