name: Fetch Weather and Post to Tandem

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes (UTC)
  workflow_dispatch:        # Optional: allow manual trigger

jobs:
  update_and_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Fetch weather and write stream.json
        run: |
          echo "import requests
import json

API_KEY = '0b4192116572f42a2606602c1a8d46c2'
CITY = 'Delft'
url = f'https://api.openweathermap.org/data/2.5/weather?q={CITY}&appid={API_KEY}&units=metric'
r = requests.get(url)
d = r.json()

with open('stream.json', 'w') as f:
    json.dump({
        'temperature': d['main']['temp'],
        'humidity': d['main']['humidity']
    }, f, indent=2)
" > fetch_weather.py
          python fetch_weather.py

      - name: Commit updated stream.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stream.json
          git commit -m "Update stream.json with live weather data" || echo "No changes to commit"
          git push

      - name: Send JSON Data to First URL (Temperature)
        run: |
          curl -X POST "https://:059UiG4ZQYeDvz9PoW600w@tandem.autodesk.com/api/v1/t
